# Generated by Django 2.2.3 on 2019-07-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('display_yn', models.BooleanField(default=False)),
                ('total_sell_count', models.PositiveSmallIntegerField()),
                ('total_cart_count', models.PositiveSmallIntegerField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_information_datetime', models.DateTimeField(auto_now=True)),
                ('category_no', models.ForeignKey(db_column='category_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='category.Category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('sell_count', models.PositiveSmallIntegerField()),
                ('cart_count', models.PositiveSmallIntegerField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_information_datetime', models.DateTimeField(auto_now=True)),
                ('item_no', models.ForeignKey(db_column='item_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='item.Item')),
            ],
            options={
                'db_table': 'item_option',
            },
        ),
        migrations.CreateModel(
            name='ItemOptionImage',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=1000)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('item_option_no', models.ForeignKey(db_column='item_option_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='item.ItemOption')),
            ],
            options={
                'db_table': 'item_option_image',
            },
        ),
        migrations.CreateModel(
            name='ItemOptionSize',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('item_option_no', models.ForeignKey(db_column='item_option_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sizes', to='item.ItemOption')),
            ],
            options={
                'db_table': 'item_option_size',
                'unique_together': {('no', 'item_option_no')},
            },
        ),
    ]
