# Generated by Django 2.2.3 on 2019-07-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('hit_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('display_yn', models.BooleanField()),
                ('total_sell_count', models.IntegerField()),
                ('total_cart_count', models.IntegerField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_information_datetime', models.DateTimeField(auto_now=True)),
                ('category_no', models.ForeignKey(db_column='category_no', on_delete=django.db.models.deletion.DO_NOTHING, to='category.Category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
