# Generated by Django 2.2.3 on 2019-07-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('sell_count', models.IntegerField()),
                ('cart_count', models.IntegerField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_information_datetime', models.DateTimeField(auto_now=True)),
                ('item_no', models.ForeignKey(db_column='item_no', on_delete=django.db.models.deletion.DO_NOTHING, to='item.Item')),
            ],
            options={
                'db_table': 'item_option',
            },
        ),
        migrations.CreateModel(
            name='ItemOptionImage',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=1000)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('item_option_no', models.ForeignKey(db_column='item_option_no', on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemOption')),
            ],
            options={
                'db_table': 'item_option_image',
            },
        ),
        migrations.CreateModel(
            name='ItemOptionSize',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('item_option_no', models.ForeignKey(db_column='item_option_no', on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemOption')),
            ],
            options={
                'db_table': 'item_option_size',
                'unique_together': {('no', 'item_option_no')},
            },
        ),
    ]
