# Generated by Django 2.2.4 on 2019-08-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190807_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoptionimage',
            name='detail',
            field=models.URLField(),
        ),
    ]
