# Generated by Django 2.2.4 on 2019-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190807_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoption',
            name='cart_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemoption',
            name='sell_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemoptionimage',
            name='detail',
            field=models.URLField(default=''),
        ),
    ]
