# Generated by Django 2.2.4 on 2019-08-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mall',
            name='tel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
