# Generated by Django 2.2.4 on 2019-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20190808_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
