# Generated by Django 2.2.4 on 2019-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='no',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
