# Generated by Django 2.2.3 on 2019-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activation_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='denied_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_cert_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='receive_email_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='receive_sms_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='seller_cert_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='seller_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
