# Generated by Django 2.2.3 on 2019-07-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_information_datetime', models.DateTimeField(auto_now=True)),
                ('mall_no', models.ForeignKey(db_column='mall_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='mall.Mall')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
