# Generated by Django 2.2.3 on 2019-07-23 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_shipping_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMember',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('order_no', models.ForeignKey(db_column='order_no', on_delete=django.db.models.deletion.DO_NOTHING, to='order.Order')),
            ],
            options={
                'db_table': 'non_member',
            },
        ),
    ]
