# Generated by Django 2.2.3 on 2019-07-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('non_member', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_quantity', models.PositiveSmallIntegerField()),
                ('item_option_size_no', models.ForeignKey(db_column='item_option_size_no', on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemOptionSize')),
                ('member_no', models.ForeignKey(blank=True, db_column='member_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to='member.Member')),
                ('non_member_no', models.ForeignKey(blank=True, db_column='non_member_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts', to='non_member.NonMember')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
