# Generated by Django 2.2.3 on 2019-07-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('non_member', '0001_initial'),
        ('item', '0002_itemoption_itemoptionimage_itemoptionsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_quantity', models.IntegerField()),
                ('item_option_size_no', models.ForeignKey(db_column='item_option_size_no', on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemOptionSize')),
                ('member_no', models.ForeignKey(blank=True, db_column='member_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
                ('non_member_no', models.ForeignKey(blank=True, db_column='non_member_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='non_member.NonMember')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
