# Generated by Django 2.2.3 on 2019-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
