# Generated by Django 2.2.3 on 2019-07-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='non_member_no',
            field=models.ForeignKey(blank=True, db_column='non_member_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='non_member.NonMember'),
        ),
    ]
