# Generated by Django 2.2.3 on 2019-07-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_no',
            field=models.ForeignKey(db_column='shipping_no', on_delete=django.db.models.deletion.DO_NOTHING, to='shipping.Shipping'),
        ),
    ]
