# Generated by Django 2.2.3 on 2019-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
